/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "example_constants.h"

namespace Example {

const exampleConstants g_example_constants;

exampleConstants::exampleConstants() {
}

} // namespace

